CREATE TABLE IF NOT EXISTS admins (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    user_id INT UNSIGNED DEFAULT NULL,
    first_name VARCHAR(100) NOT NULL,
    last_name VARCHAR(100) NOT NULL,
    position VARCHAR(100) NOT NULL,
    area VARCHAR(150) DEFAULT NULL,
    contact_no VARCHAR(30) DEFAULT NULL,
    employee_id VARCHAR(50) NOT NULL,
    department VARCHAR(100) NOT NULL,
    company_email VARCHAR(150) DEFAULT NULL,
    email VARCHAR(150) DEFAULT NULL,
    status ENUM('pending','active','inactive') NOT NULL DEFAULT 'active',
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    UNIQUE KEY admins_employee_id_unique (employee_id),
    UNIQUE KEY admins_company_email_unique (company_email),
    UNIQUE KEY admins_email_unique (email),
    KEY admins_user_id_index (user_id),
    KEY admins_department_index (department),
    KEY admins_status_index (status),
    KEY admins_created_at_index (created_at),
    CONSTRAINT fk_admins_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
