CREATE TABLE IF NOT EXISTS inhouse_sales (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    inhouse_id INT UNSIGNED DEFAULT NULL,
    create_at DATETIME DEFAULT NULL,
    user_id INT UNSIGNED NULL,
    user_type VARCHAR(50) DEFAULT NULL,
    sales_manager VARCHAR(150) NOT NULL,
    first_name VARCHAR(100) NOT NULL,
    middle_name VARCHAR(100) DEFAULT NULL,
    last_name VARCHAR(100) NOT NULL,
    contact VARCHAR(30) DEFAULT NULL,
    email VARCHAR(150) NOT NULL,
    password VARCHAR(255) DEFAULT NULL,
    photos VARCHAR(255) DEFAULT NULL,
    address VARCHAR(255) DEFAULT NULL,
    sales_category VARCHAR(100) NOT NULL,
    status ENUM('pending','active','inactive') NOT NULL DEFAULT 'pending',
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    UNIQUE KEY inhouse_email_unique (email),
    KEY inhouse_user_id_index (user_id),
    KEY inhouse_status_index (status),
    KEY inhouse_created_at_index (created_at),
    CONSTRAINT fk_inhouse_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
