CREATE TABLE IF NOT EXISTS msa_partners (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    partners_id INT UNSIGNED DEFAULT NULL,
    create_at DATETIME DEFAULT NULL,
    user_id INT UNSIGNED NULL,
    user_type VARCHAR(50) DEFAULT NULL,
    sales_manager VARCHAR(150) DEFAULT NULL,
    company_name VARCHAR(150) NOT NULL,
    first_name VARCHAR(100) DEFAULT NULL,
    middle_name VARCHAR(100) DEFAULT NULL,
    last_name VARCHAR(100) DEFAULT NULL,
    contact VARCHAR(30) DEFAULT NULL,
    email VARCHAR(150) NOT NULL,
    password VARCHAR(255) DEFAULT NULL,
    photos VARCHAR(255) DEFAULT NULL,
    area_type VARCHAR(30) NOT NULL,
    address VARCHAR(255) NOT NULL,
    sales_category VARCHAR(100) DEFAULT NULL,
    status ENUM('pending','active','inactive') NOT NULL DEFAULT 'pending',
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    UNIQUE KEY msa_email_unique (email),
    KEY msa_user_id_index (user_id),
    KEY msa_area_type_index (area_type),
    KEY msa_status_index (status),
    KEY msa_created_at_index (created_at),
    CONSTRAINT fk_msa_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
