CREATE TABLE IF NOT EXISTS asm_per_areas (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    sales_manager VARCHAR(150) NOT NULL,
    region VARCHAR(80) NOT NULL,
    province VARCHAR(120) NOT NULL,
    municipality VARCHAR(120) NOT NULL,
    validation_status ENUM('approved','pending','declined') NOT NULL DEFAULT 'pending',
    check_surf2sawa TINYINT(1) NOT NULL DEFAULT 0,
    check_fiberx TINYINT(1) NOT NULL DEFAULT 0,
    check_bida TINYINT(1) NOT NULL DEFAULT 0,
    check_sme TINYINT(1) NOT NULL DEFAULT 0,
    status ENUM('active','inactive') NOT NULL DEFAULT 'active',
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    INDEX sales_manager_index (sales_manager),
    INDEX region_index (region),
    INDEX province_index (province),
    INDEX municipality_index (municipality),
    INDEX validation_status_index (validation_status),
    INDEX status_index (status),
    INDEX created_at_index (created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
